github: [CodyTolene]
# buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
# community_bridge: []
# custom: []
# issuehunt: # Replace with a single IssueHunt username
# issuehunt: []
# ko_fi: # Replace with a single Ko-fi username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# open_collective: # Replace with a single Open Collective username
# otechie: []
# patreon: # Replace with a single Patreon username
# polar: # Replace with a single Polar username
# thanks_dev: # Replace with a single thanks.dev username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# tidelift: []
